version: '3.8'

services:
  # Serviço do MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  # Serviço do Redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_network

  # Serviço do PHP
  php:
    build:
      context: ./php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel_network

  # Serviço do Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - php

volumes:
  mysql_data:
    driver: local

networks:
  laravel_network:
    driver: bridge
